### ISSUE TITLE
Code Functionality: general expense item usability

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#23]
User stories:
[US04.03.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/83)
[US04.02.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/82)
[US04.01.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/81)

**Comment by eorodrig** [comment]
Will work on this one for a little while.

**Comment by eorodrig** [comment]
Done work for today.
Finished constructor and part of US04.01.01 (1/3)

Question regarding expense categories: Should they be an enum?

**Comment by lolicatgirls** [comment]
This 
should be satisfied 
Reopen this if still not sure about the enum question
